package com.memoryflow.service;

import com.baomidou.mybatisplus.core.MybatisConfiguration;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.metadata.TableInfoHelper;
import com.memoryflow.entity.TodoTask;
import org.apache.ibatis.builder.MapperBuilderAssistant;
import com.memoryflow.mapper.TodoListMapper;
import com.memoryflow.mapper.TodoSubtaskMapper;
import com.memoryflow.mapper.TodoTagMapper;
import com.memoryflow.mapper.TodoTaskMapper;
import com.memoryflow.mapper.TodoTaskTagMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Collections;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * 锁死「未到期的循环待办不出现在列表里」这条规则。
 * 之前完成一次会立刻把下一次摆回列表，导致可以一路连点、永远勾不完。
 */
@ExtendWith(MockitoExtension.class)
class TodoServiceVisibilityTest {

    @Mock private TodoListMapper todoListMapper;
    @Mock private TodoTaskMapper todoTaskMapper;
    @Mock private TodoSubtaskMapper todoSubtaskMapper;
    @Mock private TodoTagMapper todoTagMapper;
    @Mock private TodoTaskTagMapper todoTaskTagMapper;

    @Captor private ArgumentCaptor<LambdaQueryWrapper<TodoTask>> wrapperCaptor;

    private TodoService todoService;

    @BeforeEach
    void setUp() {
        // LambdaQueryWrapper#getTargetSql 需要实体的字段映射缓存，纯单测里手动初始化一次
        TableInfoHelper.initTableInfo(
                new MapperBuilderAssistant(new MybatisConfiguration(), ""), TodoTask.class);

        todoService = new TodoService(todoListMapper, todoTaskMapper, todoSubtaskMapper,
                todoTagMapper, todoTaskTagMapper);
    }

    @Test
    void taskQueryFiltersOutFutureAutoGeneratedOccurrences() {
        when(todoTaskMapper.selectList(any())).thenReturn(Collections.emptyList());

        todoService.getTasks(11L, null, "all", "all", "all", null, null, "custom", "asc");

        verify(todoTaskMapper).selectList(wrapperCaptor.capture());
        String sql = wrapperCaptor.getValue().getTargetSql();

        // 派生行的判定依据是 repeat_index，且必须和到期日一起出现在条件里
        assertThat(sql).contains("repeat_index");
        assertThat(sql).contains("repeat_freq");
        assertThat(sql).contains("due_date");
    }

    @Test
    void statsUseTheSameVisibilityRuleAsTheList() {
        when(todoTaskMapper.selectCount(any())).thenReturn(0L);

        todoService.getStats(11L);

        verify(todoTaskMapper, org.mockito.Mockito.atLeastOnce()).selectCount(wrapperCaptor.capture());

        // 每一次计数都要带上同一条可见性规则，否则会出现「计数里有、列表里找不到」
        assertThat(wrapperCaptor.getAllValues())
                .isNotEmpty()
                .allSatisfy(wrapper -> assertThat(wrapper.getTargetSql()).contains("repeat_index"));
    }
}
